services:
  app:
    build: .
    ports:
      - "8090:8080"                   # Access Spring Boot app from docker at http://localhost:8090
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
       mysql:
          condition: service_healthy

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "@@12GoogleKnow"
      MYSQL_DATABASE: learn
      MYSQL_USER: robert
      MYSQL_PASSWORD: "1234"
    ports:
      - "3307:3306"

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - mysql-s-data:/var/lib/mysql


volumes:
  mysql-s-data:
